### ISSUE TITLE
numpy.testing.decorators

### ISSUE THREAD

**Issue by cle-bodin** [timsainb/birdbrain#26]
Hi , I wanted to run online the zebrafinch notebooks using binder but there is the following message ( even before the password cell) :
/mnt/cube/tsainbur/conda_envs/tpy3/lib/python3.6/site-packages/tqdm/autonotebook/__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)

and when I run it I obtain : ModuleNotFoundError: No module named 'numpy.testing.decorators'

Does anybody have this error too ? How can I solve this ? 

Thanks !

**Comment by cle-bodin** [comment]
import tqdm.auto just solved it x)

**Comment by timsainb** [comment]
Ah cool. I haven't updated this repo in quite a while and there will probably be a bunch more errors due to things changing - for one, the repository that hosted the atlas moved. There are probably going to be updates to the 3d viewer that could break this code too.
